# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets
from PyQt5.QtWebEngineWidgets import *
import sys
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtWebEngineWidgets import *
import requests    


class dockdemo(QMainWindow):
    def __init__(self, parent = None):
        super(dockdemo, self).__init__(parent)
		
        layout = QHBoxLayout()

        self.browser = QWebEngineView()
        self.browser.setUrl(QUrl('https://www.google.com/?hl=fr'))

        navbar = QToolBar()
        self.addToolBar(navbar)

        back_btn = QAction('Back', self)
        back_btn.triggered.connect(self.browser.back)
        navbar.addAction(back_btn)

        forward_btn = QAction('Forward', self)
        forward_btn.triggered.connect(self.browser.forward)
        navbar.addAction(forward_btn)

        reload_btn = QAction('Reload', self)
        reload_btn.triggered.connect(self.browser.reload)
        navbar.addAction(reload_btn)

        home_btn = QAction('Home', self)
        home_btn.triggered.connect(self.navigate_home)
        navbar.addAction(home_btn)

        inspect_btn = QAction('Inspect', self)
        inspect_btn.triggered.connect(self.inspect_page)
        navbar.addAction(inspect_btn)

        self.url_bar = QLineEdit()
        self.url_bar.returnPressed.connect(self.navigate_to_url)
        navbar.addWidget(self.url_bar)

        self.browser.urlChanged.connect(self.update_url)

      
		
        self.items = QDockWidget("Historiques", self)
        self.reqs = QDockWidget("Requests", self)
        self.listWidget = QListWidget()
        self.listWidgetReqs = QListWidget()
		
        self.items.setWidget(self.listWidget)
        self.reqs.setWidget(self.listWidgetReqs)
        self.items.setFloating(False)
        self.reqs.setFloating(False)
        self.setCentralWidget(self.browser)
        self.addDockWidget(Qt.RightDockWidgetArea, self.items)
        self.addDockWidget(Qt.LeftDockWidgetArea, self.reqs)
        self.setLayout(layout)
        self.setWindowTitle("Dock demo")

        self.listWidget.itemClicked.connect(self.itemClicked_event)



    def navigate_home(self):
        self.browser.setUrl(QUrl('https://www.google.com/?hl=fr'))

    def inspect_page(self):
        print(self.browser.devType.values)

    def navigate_to_url(self):
        url = self.url_bar.text()
        self.listWidget.addItem(url)
        if(self.isSearch(url)):
            print(url)
            self.browser.setUrl(QUrl("https://www.google.com/search?q="+url+"&hl=fr"))
        else:
            self.browser.setUrl(QUrl(url))
            print(requests.get(url).content)
            #self.listWidgetReqs.addItem(requests.get(url).text)
  
    def update_url(self, q):
        self.url_bar.setText(q.toString())
        self.listWidget.addItem(q.toString())
        

    def isSearch(self,url):
        if('www.' in url or 'http://' in url or 'https://' in url):
            print(url)
            return False
        else:
            return True
    
    def itemClicked_event(self,item):
        print(item.text())
        url=item.text()
        if(self.isSearch(url)):
            self.browser.setUrl(QUrl("https://www.google.com/search?q="+url+"&hl=fr"))
        else:
            self.browser.setUrl(QUrl(url))
            print(requests.get(url).content)
            #self.listWidgetReqs.addItem(requests.get(url).text)
                
def main():
   app = QApplication(sys.argv)
   ex = dockdemo()
   ex.show()
   sys.exit(app.exec_())
	
if __name__ == '__main__':
   main()